export const SideMenuTexts = {
  dashboard: "Dashboard",
  jobs: "Jobs",
  candidates: "Candidates",
  exams: "Exams",
  admin: "Admin",
  smileBat: "SmileBat",
  main: "MAIN",
  completedExams: "Completed Exams",
  createNewExam: "Create New Exam",
  postJobs: "Post Jobs",
  assessments: "Assessments",
  sb: "SB",
  applicants: "Applicants",
  profile: "Profile",
  help: "Help",
  resumeBuilder: "Resume builder",
};

export const DataAttributeTexts = {
  tIndex: "t-index",
};

export const CandidateDashboardTexts = {
  yourActivities: "Your Activities",
  assessmentsCompleted: "Assessments Completed",
  jobsApplied: "Jobs Applied",
  interviewCalls: "Interview Calls",
  jobsCompaniesConsideringYou: "Jobs/Companies considering you",
  recommendedAssessmentsForYou: "Recommended Assessments for you",
  filter: "Filter",
};

export const AssessmentTexts = {
  askWhy: "Ask why?",
  assessmentsRequired: "Assessments Required",
};

export const CommonTexts = {
  viewStats: "View Stats",
  viewAll: "View All",
  description: "Description",
  experience: "Experience",
  email: "Email",
  mobileNo: "Mobile No.",
  city: "City",
  role: "Role",
  location: "Location",
  projectUrl: "Project URL",
  companyName: "Company Name",
  projectName: "Project Name",
  linkedInUrl: "LinkedIn Profile URL",
  githubUrl: "Github Profile URL",
  from: "From",
  to: "To",
  selectFromDate: "Select from date",
  selectToDate: "Select to date",
  addSkills: "Add skills",
  skills: "Skills",
  education: "Education",
  previouslyGeneratedAssessments: "Previously Generated Assessments",
  phone: "Phone",
  assign: "Assign",
  generateAssessment: "Generate Assessment",
  scheduleACall: "Schedule a Call",
  requiredSkills: "Required Skills",
  responsibilities: "Responsibilities",
  qualificationsOrExperienceRequired: "Experience Required",
  startAssessment: "Start Assessment",
  instructions: "Instructions",
  aGeneralInformation: "A. General Information",
  bRelatedInformation: "B. Related Information",
  instructionNote:
    "Note: The following Assessment will be a Proctored exam and duration is 30min",
  assessment: "Assessment",
  timeRemaining: "Time Remaining :",
  noJobsAvailable: "No Jobs Available",
  noAssessmentsAvailable: "No Assessments Available",
  buildAResumeForFree: "Build a resume for free ",
  WORK_EXPERIENCE: "WORK EXPERIENCE",
  SKILLS: "SKILLS",
  PROJECTS: "PROJECTS",
  EDUCATION: "EDUCATION",
  CONTACT_US: "Contact Us",
  CONTACT_US_TITLE: "Have any questions? We'd love to hear from you.",
  currentCTC: "Current CTC",
  expectedCTC: "Expected CTC",
  currentCTCPerAnnum: "Current CTC Per Annum",
  expectedCTCPerAnnum: "Expected CTC Per Annum",
  noticePeriodInDays: "Notice Period In Days",
  availableForInterview: "Available For Interview",
  currentDesignation: "Current Designation",
  achivementTasks: "Achievements/Tasks",
  submittingResults: "Submitting Results",
  loadingAssessment: "Loading Assessment",
  present: "Present",
  delete: "Delete",
};

export const ButtonTexts = {
  startNow: "Start now",
  viewDetails: "View Details",
  generateAssessment: "Generate Assessment",
  postNewJob: "Post New Job",
  cancel: "Cancel",
  postJob: "Post Job",
  generate: "Generate",
  assign: "Assign",
  send: "Send",
  saveJob: "Save Job",
  logout: "Logout",
  uploadPhoto: "Upload Photo",
  uploadResume: "Upload Resume",
  addNewExperience: "Add New Experience",
  addNewProject: "Add New Project",
  addNewResume: "Add New Resume",
  submit: "Submit",
  addNewEducation: "Add New Education",
  deleteEducation: "Delete Education",
  deleteExperience: "Delete Experience",
  deleteProject: "Delete Project",
  contactInfo: "Contact Info",
  continue: "Continue",
  prev: "Prev",
  next: "Next",
  currentlyWorkingHere: "Currently working here",
  addThisResumeToMyProfile: "Add this resume to my profile ",
  back: "Back",
  saveAndNext: "Save & Next",
  download: "Download",
  goToDashboard: "Go to Dashboard",
  editProfile: "Edit Profile",
  sendInquiry: "Send Inquiry",
  downloadResume: "Download Resume",
  goToAssessments: "Go To Assessments",
};

export const TabLabelTexts = {
  all: "All",
  completed: "Completed",
  blocked: "Blocked",
  saved: "Saved",
  pending: "Pending",
};

export const HrDashboardTexts = {
  hiringsInTheLastMonth: "Hirings in the last month",
  hiringsInProgress: "Hirings in progress",
};

export const HrApplicantTexts = {
  selectMultiple: "Select Multiple",
};

export const PostJobsTexts = {
  previouslyPostedJobs: "Previously posted jobs",
  addSkillsRequired: "Add Skills Required",
  qualificationRequired: "Qualification Required",
  experienceRequired: "Experience in years",
  jobTitle: "Job title",
  jobLocation: "Job Location",
  companyName: "Company Name",
  salaryBudget: "Salary Budget for this job",
};

export const ModalTexts = {
  postANewJobs: "Post a new Job",
  generateAssessment: "Generate Assessment",
  assignAssessment: "Assign Assessment",
  editJob: "Edit the job",
  contactInfo: "Contact Info",
  jobDescription: "Job Description",
  submittingAssessment: "Submitting Assessment...",
  help: "help",
  scheduleCall: "Schedule Call",
};

export const ProfileTexts = {
  basicInfo: "Basic Info",
  experience: "Experience",
  projects: "Projects",
  skills: "Skills",
  education: "Education",
  resume: "Resume",
  editInfo: "Edit Info",
  descriptionAboutYou: "Description about you",
  compensation: "Compensation",
  socialNetworks: "Social Networks",
};

export const TextFieldLabelsAndTexts = {
  name: "Name",
  enterFullName: "Enter full name",
  enterEmail: "Enter email",
  enterPhoneOrMobileNumber: "Enter phone/mobile number",
  enterCityOrCountry: "Enter city/country",
  enterOrgOrCompanyName: "Enter your organization/company name",
  enterYourRole: "Enter role/designation",
  enterUniversityOrCollegeName: "Enter University/College Name",
  universityOrCollegeName: "University/College Name",
  degree: "Degree",
  selectDegree: "Select degree",
  fieldOfStudy: "Field of study",
  jobsAssessedFor: "Jobs Assessed For",
  defaultOrPreviouslyGeneratedAssessments:
    "Default/Previously Generated Assessments",
  skillsList: "Skills List",
  difficultyLevel: "Difficulty Level",
  selectEmployementType: "Select employment type",
  employmentType: "Employment Type",
  city: "City",
  address: "Address",
  enterLocation: "Enter location",
};
